apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: todo-postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: todo-postgres
  clusterIP: None
